### ISSUE TITLE
AMap is not defined

### ISSUE THREAD

**Issue by LeeLinchang** [LiuJi-Jim/amap-vue#10]
需要用到new Amap.ContextMenu()等其他东西时，会报错 AMap is not defined

**Comment by LeeLinchang** [comment]
引入loadAmap()就行了，从饿了么迁移过来，高德1.4和2.0的API差别也有点大，坑有点多

**Comment by LiuJi-Jim** [comment]
@LeeLinchang 目前@amap/amap-vue主要面向高德地图2.0场景，历史版本@amap/amap-vue@1.4.x基本不维护。并且以我在项目中实际需求自给自足为准，暂无社区化运作的打算。
如果你使用的是高德地图1.4.x，那么我建议你使用@amap/amap-vue的1.4.x版本，或者ElemeFE开发的vue-amap。
