### ISSUE TITLE
无法获取高德地图的原生对象

### ISSUE THREAD

**Issue by yoshiiiiiihiko** [LiuJi-Jim/amap-vue#11]
用文档上所说的this.$refs.xxx.$map（xxx为自定义的ref id），打印结果为null。

**Comment by yoshiiiiiihiko** [comment]
是我哪里搞错了吗？

**Comment by LiuJi-Jim** [comment]
请参考[小区排行](https://jimnox.gitee.io/amap-vue/examples/top-home-rank.html)示例中的使用方法

**Comment by yoshiiiiiihiko** [comment]
非常感谢。
另外，目前在创建地图前，支持配置的属性没有是否开启国外地图的属性(vectorMapForeign)，或者有什么其他办法可以做到吗？
参考的海外LBS链接如下：
https://a.amap.com/lbs/static/pdf/%E6%B5%B7%E5%A4%96%E5%9C%B0%E5%9B%BEJS%20API%20V1.0.0.pdf

**Comment by LiuJi-Jim** [comment]
> 非常感谢。
> 另外，目前在创建地图前，支持配置的属性没有是否开启国外地图的属性(vectorMapForeign)，或者有什么其他办法可以做到吗？
> 参考的海外LBS链接如下：
> https://a.amap.com/lbs/static/pdf/%E6%B5%B7%E5%A4%96%E5%9C%B0%E5%9B%BEJS%20API%20V1.0.0.pdf

Hi，需求收到，因为海外地图是需要商业授权的，所以我这边对这个属性不了解就没做进去=.=
近期会给地图相关组件增加一个`extra`之类的属性用来透传其他未包装的初始化属性，以方便在跟不上官方更新情况下还能用上新的功能。

**Comment by yoshiiiiiihiko** [comment]
这个做法太棒了 : )，这样灵活性会大大提升。期待大神的更新。

**Comment by LiuJi-Jim** [comment]
> 这个做法太棒了 : )，这样灵活性会大大提升。期待大神的更新。

2.x版本更新到2.0.11，legacy版本更新到1.4.2。包括`<Amap>`在内各个组件都支持`extraOptions`可选属性了，类型为`object`，就是简单地在初始化地图/组件的时候会透传一下……

**Comment by yoshiiiiiihiko** [comment]
老哥稳👍
