### ISSUE TITLE
按需引入问题

### ISSUE THREAD

**Issue by linwei921219** [LiuJi-Jim/amap-vue#14]
使用文档方法按需引入，在组件中
import Amap from '@amap/amap-vue/lib/Amap';
import AmapMarker from '@amap/amap-vue/lib/Marker';
 
出现以下报错，翻看安装的依赖文件夹中并未找到对应文件
 
 
These dependencies were not found:
 
* @amap/amap-vue/lib/Amap in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/front/ContactUs/index.vue?vue&type=script&lang=js&
* @amap/amap-vue/lib/Marker in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/front/ContactUs/index.vue?vue&type=script&lang=js&
 
To install them, you can run: npm install --save @amap/amap-vue/lib/Amap @amap/amap-vue/lib/Marker

**Comment by LiuJi-Jim** [comment]
抱歉，文档有误，应为：
```javascript
import Amap from '@amap/amap-vue/lib/amap';
import AmapMarker from '@amap/amap-vue/lib/marker';
```
[相关文档](https://jimnox.gitee.io/amap-vue/intro/installation.html)已更新
