### ISSUE TITLE
标注和标注图层的性能问题

### ISSUE THREAD

**Issue by beary** [LiuJi-Jim/amap-vue#4]
使用 amap-labels-layer 和 amap-label-marker 进行标注时性能低下，data 数据小于100 时还比较流畅，但如果标注点达到 500 个左右就开始卡顿，2000 个页面无响应。

但官方文档渲染 30000 点都没有明显卡顿：https://lbs.amap.com/api/jsapi-v2/example/mass-markers/labelmarker-mass

```pug
<template lang="pug">
  v-container.fill-height
    amap(key="key" map-style="amap://styles/whitesmoke" :center="data[0]")
      amap-labels-layer(:zooms="[3, 20]")
        amap-label-marker(v-for="(pos, i) in data.slice(0, 100)" :key="i" :position="pos" :icon="icon")
</template>
```

**Comment by LiuJi-Jim** [comment]
大量数据绑定容易引发vue的`defineReactiveGetter`占用时间很多和卡顿，这种情况可以对数据使用Object.freeze，避免它被vue进行响应式包装，但自然也会失去一些响应式的开发优势。
